import { StyleSheet } from "react-native";

const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: "#f9fafb" },
  hero: { backgroundColor: "#fff", padding: 28, paddingTop: 52, alignItems: "center", borderBottomWidth: 1, borderBottomColor: "#f3f4f6" },
  heroLogo: { fontSize: 26, fontWeight: "900", color: "#111827" },
  heroSub: { fontSize: 13, color: "#6b7280", marginTop: 4 },
  heroBadge: { backgroundColor: "#dcfce7", paddingVertical: 4, paddingHorizontal: 14, borderRadius: 20, marginTop: 10 },
  heroBadgeText: { color: "#166534", fontWeight: "700", fontSize: 12 },
  sectionLabel: { fontSize: 11, fontWeight: "700", color: "#9ca3af", paddingHorizontal: 16, paddingTop: 20, paddingBottom: 10 },
  subjectCard: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", padding: 18, borderWidth: 1, borderRadius: 14, marginHorizontal: 16, marginBottom: 10 },
  subjectLeft: { flexDirection: "row", alignItems: "center", flex: 1, marginRight: 10 },
  subjectIcon: { fontSize: 28, marginRight: 14 },
  subjectName: { fontSize: 18, fontWeight: "700" },
  subjectDesc: { fontSize: 12, color: "#6b7280", marginTop: 2 },
  csPill: { paddingVertical: 4, paddingHorizontal: 10, borderRadius: 20 },
  tutorBanner: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", margin: 16, padding: 18, backgroundColor: "#fff", borderWidth: 1, borderColor: "#e5e7eb", borderRadius: 14 },
  tutorTextBlock: { flex: 1, marginRight: 12 },
  tutorTitle: { fontSize: 15, fontWeight: "700", color: "#111827", marginBottom: 3 },
  tutorDesc: { fontSize: 12, color: "#6b7280" },
  tutorBtn: { backgroundColor: "#16a34a", paddingVertical: 10, paddingHorizontal: 18, borderRadius: 8, flexShrink: 0 },
  adBanner: { alignItems: "center", justifyContent: "center", marginHorizontal: 16, marginTop: 10, padding: 12, backgroundColor: "#f3f4f6", borderRadius: 8, borderWidth: 1, borderColor: "#e5e7eb" },
  adText: { color: "#9ca3af", fontSize: 12 },
  topBar: { flexDirection: "row", alignItems: "center", padding: 14, paddingTop: 44, borderBottomWidth: 1 },
  backBtn: { color: "#6b7280", fontSize: 14, marginRight: 10 },
  topBarTitle: { fontSize: 16, fontWeight: "700", flex: 1 },
  topicCard: { backgroundColor: "#fff", borderWidth: 1, borderRadius: 12, padding: 14, marginBottom: 10 },
  topicRow: { flexDirection: "row", alignItems: "flex-start", marginBottom: 12 },
  topicNum: { fontSize: 18, fontWeight: "900", width: 32 },
  topicMid: { flex: 1 },
  topicNameRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  topicName: { fontSize: 14, fontWeight: "700", color: "#111827", marginBottom: 3, flexShrink: 1, marginRight: 8 },
  topicSub: { fontSize: 11, color: "#9ca3af" },
  topicBtns: { flexDirection: "row" },
  practiceBtn: { flex: 1, paddingVertical: 10, borderRadius: 8, marginRight: 8, alignItems: "center" },
  bookBtn: { flex: 1, paddingVertical: 10, borderRadius: 8, borderWidth: 1, backgroundColor: "#fff", alignItems: "center" },
  bookBtnText: { fontWeight: "700" },
  btnText: { color: "#fff", fontWeight: "700", textAlign: "center" },
  lockedPill: { backgroundColor: "#f3f4f6", paddingVertical: 2, paddingHorizontal: 8, borderRadius: 10, flexShrink: 0 },
  lockedPillText: { fontSize: 10, fontWeight: "700", color: "#9ca3af" },
  progressRow: { flexDirection: "row", paddingHorizontal: 16, paddingVertical: 10, backgroundColor: "#fff" },
  progressSeg: { flex: 1, height: 5, borderRadius: 3, marginHorizontal: 2 },
  quizTopicLabel: { flex: 1, fontSize: 12, color: "#374151", fontWeight: "600" },
  qCount: { fontSize: 13, fontWeight: "700", color: "#16a34a" },
  subtopicChip: { backgroundColor: "#dcfce7", alignSelf: "flex-start", paddingVertical: 3, paddingHorizontal: 10, borderRadius: 20, marginBottom: 10 },
  subtopicText: { color: "#166534", fontSize: 11, fontWeight: "700" },
  qText: { fontSize: 16, fontWeight: "700", color: "#111827", marginBottom: 16, lineHeight: 24 },
  optBtn: { flexDirection: "row", alignItems: "center", borderWidth: 1, borderRadius: 10, padding: 12, marginBottom: 8 },
  optLabel: { width: 28, height: 28, borderRadius: 6, alignItems: "center", justifyContent: "center", marginRight: 10 },
  optLabelText: { fontSize: 12, fontWeight: "700" },
  optText: { flex: 1, fontSize: 13, lineHeight: 20 },
  explanBox: { borderWidth: 1, borderRadius: 10, padding: 14, marginTop: 8, marginBottom: 12 },
  explanTitle: { fontWeight: "700", fontSize: 13, marginBottom: 6 },
  explanText: { fontSize: 12, color: "#374151", lineHeight: 18 },
  nextBtn: { backgroundColor: "#16a34a", paddingVertical: 13, borderRadius: 10 },
  resultCard: { backgroundColor: "#fff", borderWidth: 1, borderColor: "#e5e7eb", borderRadius: 20, padding: 28, alignItems: "center" },
  resultIcon: { fontSize: 44, marginBottom: 10 },
  resultPct: { fontSize: 58, fontWeight: "900" },
  resultGrade: { fontSize: 18, fontWeight: "700", marginTop: 8, marginBottom: 4 },
  resultDetail: { fontSize: 14, color: "#6b7280", marginBottom: 2 },
  resultTopic: { fontSize: 12, color: "#9ca3af", marginBottom: 18 },
  breakdownRow: { flexDirection: "row", marginBottom: 22 },
  bdDot: { width: 32, height: 32, borderRadius: 8, alignItems: "center", justifyContent: "center", marginHorizontal: 3 },
  resultBtn: { width: "100%", paddingVertical: 13, borderRadius: 10, marginBottom: 8 },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "flex-end" },
  modalCard: { backgroundColor: "#fff", borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 24, paddingBottom: 40 },
  modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 6 },
  modalTitle: { fontSize: 18, fontWeight: "700", color: "#111827" },
  modalClose: { fontSize: 20, color: "#9ca3af", paddingHorizontal: 8 },
  modalTopic: { fontSize: 13, color: "#16a34a", fontWeight: "700", marginBottom: 16 },
  inputLabel: { fontSize: 12, fontWeight: "600", color: "#374151", marginBottom: 6 },
  input: { borderWidth: 1, borderColor: "#e5e7eb", borderRadius: 8, padding: 12, fontSize: 14, marginBottom: 14, color: "#111827" },
  sessionBox: { backgroundColor: "#f9fafb", borderRadius: 10, padding: 14, marginBottom: 16 },
  sessionLabel: { fontSize: 10, fontWeight: "700", color: "#9ca3af", marginBottom: 10 },
  sessionRow: { flexDirection: "row", justifyContent: "space-between", marginBottom: 6 },
  sessionName: { fontSize: 13, color: "#374151", flex: 1 },
  sessionPrice: { fontSize: 13, fontWeight: "700", color: "#16a34a" },
  whatsappBtn: { backgroundColor: "#16a34a", paddingVertical: 14, borderRadius: 10 },
});

export default s;
