// Auto-generated by scaffold_bio_phys.js. Edit question files, not this header.
import intro from "./chemistry/intro";
import atom from "./chemistry/atom";
import separation from "./chemistry/separation";
import periodic from "./chemistry/periodic";
import bonding from "./chemistry/bonding";
import stoich from "./chemistry/stoich";
import states from "./chemistry/states";
import acids from "./chemistry/acids";
import kinetics from "./chemistry/kinetics";
import redox from "./chemistry/redox";
import organic from "./chemistry/organic";
import industry from "./chemistry/industry";
import biochem from "./chemistry/biochem";
import metals from "./chemistry/metals";
import practical from "./chemistry/practical";
import secA_classification from "./biology/secA-classification";
import secA_organization from "./biology/secA-organization";
import secA_forms_of_cells from "./biology/secA-forms-of-cells";
import secA_cell_structure from "./biology/secA-cell-structure";
import secA_cell_environment from "./biology/secA-cell-environment";
import secA_cell_properties from "./biology/secA-cell-properties";
import secA_supporting_tissues from "./biology/secA-supporting-tissues";
import secA_transport from "./biology/secA-transport";
import secA_respiratory_system from "./biology/secA-respiratory-system";
import secA_excretory_systems from "./biology/secA-excretory-systems";
import secA_internal_environment from "./biology/secA-internal-environment";
import secA_hormonal from "./biology/secA-hormonal";
import secA_nervous from "./biology/secA-nervous";
import secA_sense_organs from "./biology/secA-sense-organs";
import secA_reproduction from "./biology/secA-reproduction";
import secA_plant_nutrition from "./biology/secA-plant-nutrition";
import secA_animal_nutrition from "./biology/secA-animal-nutrition";
import secA_ecosystem from "./biology/secA-ecosystem";
import secA_ecol_factors from "./biology/secA-ecol-factors";
import secA_ecol_measurement from "./biology/secA-ecol-measurement";
import secA_food_webs from "./biology/secA-food-webs";
import secA_energy_flow from "./biology/secA-energy-flow";
import secA_ecol_management from "./biology/secA-ecol-management";
import secA_ecol_population from "./biology/secA-ecol-population";
import secA_microorganisms from "./biology/secA-microorganisms";
import secA_conservation_resources from "./biology/secA-conservation-resources";
import secA_conservation_ways from "./biology/secA-conservation-ways";
import secA_variation_morphological from "./biology/secA-variation-morphological";
import secA_variation_physiological from "./biology/secA-variation-physiological";
import secA_genetics_terms from "./biology/secA-genetics-terms";
import secA_genetics_transmission from "./biology/secA-genetics-transmission";
import secA_genetics_probability from "./biology/secA-genetics-probability";
import secA_genetics_linkage from "./biology/secA-genetics-linkage";
import secA_genetics_applications from "./biology/secA-genetics-applications";
import secA_behavioural_adaptation from "./biology/secA-behavioural-adaptation";
import secA_evolution from "./biology/secA-evolution";
import secC_cell_theory from "./biology/secC-cell-theory";
import secC_irritability from "./biology/secC-irritability";
import secC_excretory from "./biology/secC-excretory";
import secC_sense_organs from "./biology/secC-sense-organs";
import secC_reproduction from "./biology/secC-reproduction";
import secC_nitrogen_cycle from "./biology/secC-nitrogen-cycle";
import secC_modes_nutrition from "./biology/secC-modes-nutrition";
import secC_alimentary from "./biology/secC-alimentary";
import secC_feeding_habits from "./biology/secC-feeding-habits";
import secC_components from "./biology/secC-components";
import secC_energy_transform from "./biology/secC-energy-transform";
import secC_nutrient_cycling from "./biology/secC-nutrient-cycling";
import secC_management from "./biology/secC-management";
import secC_habitats from "./biology/secC-habitats";
import secC_agric_relevance from "./biology/secC-agric-relevance";
import secC_microorganisms from "./biology/secC-microorganisms";
import secC_crime_detection from "./biology/secC-crime-detection";
import secC_blood_transfusion from "./biology/secC-blood-transfusion";
import secC_paternity from "./biology/secC-paternity";
import secC_adaptation_survival from "./biology/secC-adaptation-survival";
import secC_structural_adaptation from "./biology/secC-structural-adaptation";
import secC_adaptive_colouration from "./biology/secC-adaptive-colouration";
import p1_concepts_of_matter from "./physics/p1-concepts-of-matter";
import p1_quantities_units from "./physics/p1-quantities-units";
import p1_position_distance from "./physics/p1-position-distance";
import p1_mass_weight from "./physics/p1-mass-weight";
import p1_time from "./physics/p1-time";
import p1_fluid_at_rest from "./physics/p1-fluid-at-rest";
import p1_motion from "./physics/p1-motion";
import p1_speed_velocity from "./physics/p1-speed-velocity";
import p1_acceleration from "./physics/p1-acceleration";
import p1_scalars_vectors from "./physics/p1-scalars-vectors";
import p1_equilibrium_forces from "./physics/p1-equilibrium-forces";
import p1_shm from "./physics/p1-shm";
import p1_newtons_laws from "./physics/p1-newtons-laws";
import p2_energy from "./physics/p2-energy";
import p2_work_energy_power from "./physics/p2-work-energy-power";
import p2_heat_energy from "./physics/p2-heat-energy";
import p3_production_waves from "./physics/p3-production-waves";
import p3_types_waves from "./physics/p3-types-waves";
import p3_properties_waves from "./physics/p3-properties-waves";
import p3_light_waves from "./physics/p3-light-waves";
import p3_electromagnetic_waves from "./physics/p3-electromagnetic-waves";
import p3_sound_waves from "./physics/p3-sound-waves";
import p4_fields_properties from "./physics/p4-fields-properties";
import p4_gravitational_field from "./physics/p4-gravitational-field";
import p4_electric_field from "./physics/p4-electric-field";
import p4_magnetic_field from "./physics/p4-magnetic-field";
import p4_electromagnetic_field from "./physics/p4-electromagnetic-field";
import p5_ac_circuits from "./physics/p5-ac-circuits";
import p5_structure_atom from "./physics/p5-structure-atom";
import p5_structure_nucleus from "./physics/p5-structure-nucleus";
import p5_wave_particle from "./physics/p5-wave-particle";
import all_derived_dimensions from "./physics/all-derived-dimensions";
import all_projectile from "./physics/all-projectile";
import all_satellites_rockets from "./physics/all-satellites-rockets";
import all_elastic_solids from "./physics/all-elastic-solids";
import all_fibre_optics from "./physics/all-fibre-optics";
import all_laser from "./physics/all-laser";
import all_magnetic_materials from "./physics/all-magnetic-materials";
import all_conduction_liquids from "./physics/all-conduction-liquids";
import all_structure_of_matter from "./physics/all-structure-of-matter";
import all_wave_particle from "./physics/all-wave-particle";
const QUESTIONS = {
  intro,
  atom,
  separation,
  periodic,
  bonding,
  stoich,
  states,
  acids,
  kinetics,
  redox,
  organic,
  industry,
  biochem,
  metals,
  practical,
  "secA-classification": secA_classification,
  "secA-organization": secA_organization,
  "secA-forms-of-cells": secA_forms_of_cells,
  "secA-cell-structure": secA_cell_structure,
  "secA-cell-environment": secA_cell_environment,
  "secA-cell-properties": secA_cell_properties,
  "secA-supporting-tissues": secA_supporting_tissues,
  "secA-transport": secA_transport,
  "secA-respiratory-system": secA_respiratory_system,
  "secA-excretory-systems": secA_excretory_systems,
  "secA-internal-environment": secA_internal_environment,
  "secA-hormonal": secA_hormonal,
  "secA-nervous": secA_nervous,
  "secA-sense-organs": secA_sense_organs,
  "secA-reproduction": secA_reproduction,
  "secA-plant-nutrition": secA_plant_nutrition,
  "secA-animal-nutrition": secA_animal_nutrition,
  "secA-ecosystem": secA_ecosystem,
  "secA-ecol-factors": secA_ecol_factors,
  "secA-ecol-measurement": secA_ecol_measurement,
  "secA-food-webs": secA_food_webs,
  "secA-energy-flow": secA_energy_flow,
  "secA-ecol-management": secA_ecol_management,
  "secA-ecol-population": secA_ecol_population,
  "secA-microorganisms": secA_microorganisms,
  "secA-conservation-resources": secA_conservation_resources,
  "secA-conservation-ways": secA_conservation_ways,
  "secA-variation-morphological": secA_variation_morphological,
  "secA-variation-physiological": secA_variation_physiological,
  "secA-genetics-terms": secA_genetics_terms,
  "secA-genetics-transmission": secA_genetics_transmission,
  "secA-genetics-probability": secA_genetics_probability,
  "secA-genetics-linkage": secA_genetics_linkage,
  "secA-genetics-applications": secA_genetics_applications,
  "secA-behavioural-adaptation": secA_behavioural_adaptation,
  "secA-evolution": secA_evolution,
  "secC-cell-theory": secC_cell_theory,
  "secC-irritability": secC_irritability,
  "secC-excretory": secC_excretory,
  "secC-sense-organs": secC_sense_organs,
  "secC-reproduction": secC_reproduction,
  "secC-nitrogen-cycle": secC_nitrogen_cycle,
  "secC-modes-nutrition": secC_modes_nutrition,
  "secC-alimentary": secC_alimentary,
  "secC-feeding-habits": secC_feeding_habits,
  "secC-components": secC_components,
  "secC-energy-transform": secC_energy_transform,
  "secC-nutrient-cycling": secC_nutrient_cycling,
  "secC-management": secC_management,
  "secC-habitats": secC_habitats,
  "secC-agric-relevance": secC_agric_relevance,
  "secC-microorganisms": secC_microorganisms,
  "secC-crime-detection": secC_crime_detection,
  "secC-blood-transfusion": secC_blood_transfusion,
  "secC-paternity": secC_paternity,
  "secC-adaptation-survival": secC_adaptation_survival,
  "secC-structural-adaptation": secC_structural_adaptation,
  "secC-adaptive-colouration": secC_adaptive_colouration,
  "p1-concepts-of-matter": p1_concepts_of_matter,
  "p1-quantities-units": p1_quantities_units,
  "p1-position-distance": p1_position_distance,
  "p1-mass-weight": p1_mass_weight,
  "p1-time": p1_time,
  "p1-fluid-at-rest": p1_fluid_at_rest,
  "p1-motion": p1_motion,
  "p1-speed-velocity": p1_speed_velocity,
  "p1-acceleration": p1_acceleration,
  "p1-scalars-vectors": p1_scalars_vectors,
  "p1-equilibrium-forces": p1_equilibrium_forces,
  "p1-shm": p1_shm,
  "p1-newtons-laws": p1_newtons_laws,
  "p2-energy": p2_energy,
  "p2-work-energy-power": p2_work_energy_power,
  "p2-heat-energy": p2_heat_energy,
  "p3-production-waves": p3_production_waves,
  "p3-types-waves": p3_types_waves,
  "p3-properties-waves": p3_properties_waves,
  "p3-light-waves": p3_light_waves,
  "p3-electromagnetic-waves": p3_electromagnetic_waves,
  "p3-sound-waves": p3_sound_waves,
  "p4-fields-properties": p4_fields_properties,
  "p4-gravitational-field": p4_gravitational_field,
  "p4-electric-field": p4_electric_field,
  "p4-magnetic-field": p4_magnetic_field,
  "p4-electromagnetic-field": p4_electromagnetic_field,
  "p5-ac-circuits": p5_ac_circuits,
  "p5-structure-atom": p5_structure_atom,
  "p5-structure-nucleus": p5_structure_nucleus,
  "p5-wave-particle": p5_wave_particle,
  "all-derived-dimensions": all_derived_dimensions,
  "all-projectile": all_projectile,
  "all-satellites-rockets": all_satellites_rockets,
  "all-elastic-solids": all_elastic_solids,
  "all-fibre-optics": all_fibre_optics,
  "all-laser": all_laser,
  "all-magnetic-materials": all_magnetic_materials,
  "all-conduction-liquids": all_conduction_liquids,
  "all-structure-of-matter": all_structure_of_matter,
  "all-wave-particle": all_wave_particle,
};

export default QUESTIONS;
