export default [
  {
    heading: "What active transport is",
    body: "Active transport is the movement of substances across a cell membrane from a region of lower concentration to a region of higher concentration — that is, against the concentration gradient. Because this is the opposite of what diffusion would do, the cell must supply energy, usually as ATP generated by respiration. The process is therefore 'active' rather than passive. It lets a cell accumulate materials that are rare outside or remove wastes that are already concentrated inside, things diffusion alone could never achieve.",
  },
  {
    heading: "Why energy is required",
    body: "Moving a particle uphill against its gradient is like pushing a load up a hill: it will not happen spontaneously and work must be done. The energy comes from ATP, the universal energy currency of the cell, which is hydrolysed to ADP and phosphate to release usable energy. Without a steady supply of ATP — from respiration — active transport stops. This is why active transport is faster in active, well-fed cells and slows or halts when a cell is poisoned or starved of oxygen.",
  },
  {
    heading: "The mechanism — carrier proteins and pumps",
    body: "Active transport is carried out by specific carrier (pump) proteins embedded in the membrane. The substance first binds to a receptor site on the carrier, then ATP provides the energy that makes the protein change shape and carry the molecule across to the other side, where it is released. Because each carrier is specific to one substance or a small group, the cell can select exactly what it imports or exports. After the cycle the protein returns to its original shape ready to bind another particle.",
  },
  {
    heading: "Example — root hair cells",
    body: "Root hairs are long, thin extensions of root epidermal cells that greatly increase the surface area for absorption from the soil. Soil solution is usually much more dilute than the cell sap inside, so mineral ions such as nitrate, potassium and phosphate cannot enter by diffusion. Instead, root hairs use active transport to pump these ions from the dilute soil into the more concentrated cell, spending ATP to do so. This is how plants obtain the mineral nutrients essential for growth even from poor soils.",
  },
  {
    heading: "Example — absorbing food in the gut",
    body: "After digestion, glucose and amino acids in the small intestine are often at a lower concentration in the gut lumen than in the blood of the villus capillaries. Diffusion alone could not move them in, so the epithelial cells of the villi use active transport (and co-transport) to carry these nutrients into the blood against the gradient. This is why digested food is absorbed almost completely rather than being lost. The same principle lets cells reclaim useful molecules the kidneys would otherwise excrete.",
  },
  {
    heading: "Example — the sodium–potassium pump",
    body: "Animal cells, especially nerve and muscle cells, rely on the sodium–potassium pump to maintain the ion gradients that power electrical signalling. For each cycle it uses ATP to push three sodium ions out of the cell and pull two potassium ions in, both against their gradients. This builds the uneven charge across the membrane that a nerve impulse depends on. It is a clear, vital example of active transport maintaining a condition diffusion would constantly try to erase.",
  },
  {
    heading: "Active transport vs diffusion and facilitated diffusion",
    body: "Diffusion and facilitated diffusion both move substances down their gradient and need no energy; active transport moves against the gradient and needs ATP. Facilitated diffusion uses protein channels but is still passive and cannot concentrate a substance. Active transport is the only one of the three that can build up a high internal concentration from a low external one. Knowing which process operates tells you whether the cell is spending energy and whether a gradient is being maintained or abolished.",
  },
  {
    heading: "Factors that affect active transport",
    body: "Because active transport depends on respiration, anything that limits ATP production slows it: low temperature (less enzyme activity), lack of oxygen (less aerobic ATP), or metabolic poisons such as cyanide that block respiratory enzymes. A shortage of carrier proteins also limits the rate, as does competition between similar ions for the same carrier. Unlike simple diffusion, active transport can be saturated — once every carrier is busy, moving more requires more carriers, not a steeper gradient.",
  },
  {
    heading: "Why active transport matters",
    body: "Active transport lets organisms control their internal environment independently of their surroundings — a defining feature of life. It allows plants to mine scarce minerals, animals to absorb nearly all their food, nerves to fire, and cells to expel toxins and pump ions where they are needed. Without it, cells could never concentrate substances above their environment and homeostasis would be impossible. It is, in effect, the molecular machinery of living regulation.",
  },
  {
    heading: "Common misconceptions cleared",
    body: "Active transport requires energy (ATP) and moves against the gradient — if movement is down the gradient and needs no energy, that is diffusion or facilitated diffusion, not active transport. It is not the same as osmosis, which moves only water passively. The process also needs living, respiring cells with working carriers, so it stops the moment the cell dies or is poisoned. Finally, it is highly specific: a carrier for one ion will not generally carry an unrelated one.",
  },
];
