// Regenerates study/registry.js from the folder tree.
// Metro rejects dynamic require(), so every topic index is listed with a STATIC
// literal require. Run: node scripts/genStudyRegistry.js
const fs = require("fs");
const path = require("path");

const STUDY = path.join(__dirname, "..", "study");
const SUBJECTS = ["chemistry", "biology", "physics"];

const entries = [];
for (const subj of SUBJECTS) {
  const subjDir = path.join(STUDY, subj);
  if (!fs.existsSync(subjDir)) continue;
  for (const topic of fs.readdirSync(subjDir).sort()) {
    const idx = path.join(subjDir, topic, "index.js");
    if (fs.existsSync(idx)) {
      entries.push(`  "${subj}/${topic}": () => require("./${subj}/${topic}/index").default,`);
    }
  }
}

const out = `// AUTO-GENERATED by scripts/genStudyRegistry.js — do not hand-edit.
// Maps "subjectId/topicId" -> literal require thunk for that topic's study index.
// Metro rejects dynamic require(), so every path must be a static literal here.
const map = {
${entries.join("\n")}
};

export default map;
`;

fs.writeFileSync(path.join(STUDY, "registry.js"), out);
console.log(`Wrote study/registry.js with ${entries.length} topic entries.`);
